replicaCount: 1

image:
  repository: dockersamples/examplevotingapp_worker
  tag: latest
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

hpa:
  minReplicas: 1
  maxReplicas: 3
  cpuUtilization: 70
