apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: voting-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/khaoula-dr/devops-control-tower.git
    targetRevision: HEAD
    path: helm
  destination:
    server: https://kubernetes.default.svc
    namespace: voting
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    # AJOUTE CETTE SECTION CI-DESSOUS
    retry:
      limit: 5 # Nombre de tentatives de synchronisation en cas d'échec
      backoff:
        duration: 10s # Attente de 10s après le premier échec
        factor: 2 # Double le temps d'attente à chaque tentative (10s, 20s, 40s...)
        maxDuration: 3m # Ne dépasse pas 3 minutes d'attente
